{{- if and .Values.ingress.enabled .Values.zyvorApi.agentMtls.enabled .Values.ingress.hosts.agentMtls }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zyvor-agent-mtls-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.agentMtls }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: zyvor-api
                port:
                  number: 8443
{{- end }}
