apiVersion: v1
kind: Secret
metadata:
  name: zyvor-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.postgresql.password | quote }}
  minio-access-key: {{ .Values.minio.accessKey | quote }}
  minio-secret-key: {{ .Values.minio.secretKey | quote }}
