{{- if .Values.kubevirt.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zyvor-api
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zyvor-api-kubevirt
rules:
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines", "virtualmachineinstances"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["subresources.kubevirt.io"]
    resources:
      - virtualmachines/restart
      - virtualmachines/start
      - virtualmachines/stop
      - virtualmachineinstances/freeze
      - virtualmachineinstances/unfreeze
      - virtualmachineinstances/softreboot
    verbs: ["update"]
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["datavolumes"]
    verbs: ["get", "list", "create", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["zeus.zyvor.dev"]
    resources: ["vmguestagents", "vmguestagents/status", "vmtoolspolicies", "vmtoolspolicies/status", "vmtoolsbundles", "vmtoolsbundles/status"]
    verbs: ["get", "list", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zyvor-api-kubevirt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zyvor-api-kubevirt
subjects:
  - kind: ServiceAccount
    name: zyvor-api
    namespace: {{ .Values.namespace }}
{{- end }}
